import openai
import base64
import subprocess
import tempfile
import logging
from markupsafe import escape
import re
from odoo import models, fields, api

_logger = logging.getLogger(__name__)

class ManualGenerator(models.Model):
    _name = 'manual.generator'
    _description = 'AI-Based Functional User Manual Generator'

    name = fields.Char(default="AI Functional Manual")
    module_ids = fields.Many2many('ir.module.module', string="Modules")
    content = fields.Html("Generated Manual", compute="_generate_manual_ai", store=True)
    manual_file = fields.Binary("Downloadable Manual")
    manual_filename = fields.Char("Filename", default="ai_user_manual.pdf")

    def call_openrouter(self, prompt):
        print("333333333333333333333333333333",prompt)

        api_key = self.env['ir.config_parameter'].sudo().get_param('openrouter.api_key')
        print("333333333333333333333333333333",api_key)
        if not api_key:
            return "⚠️ OpenRouter API key not configured."

        try:
            # Create the new-style OpenAI client (as of SDK v1+)
            client = openai.OpenAI(
            api_key=api_key,
            base_url="https://openrouter.ai/api/v1"
        )

            # Use the correct new-style chat API
            response = client.chat.completions.create(
            model="mistralai/mistral-7b-instruct",
            messages=[
                {"role": "user", "content": prompt}
            ],
            temperature=0.7
        )

            return response.choices[0].message.content.strip()

        except Exception as e:
            return f"❌ OpenRouter Error: {str(e)}"

    def markdown_to_html(self, text):
        text = escape(text)  # Prevent XSS
        text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)  # Bold
        text = re.sub(r"\_(.+?)\_", r"<em>\1</em>", text)              # Italics
        text = re.sub(r"^\d+\.\s(.+)", r"<h3>\1</h3>", text, flags=re.MULTILINE)  # Sections
        text = re.sub(r"- (.+)", r"<li>\1</li>", text)  # Bullets
        text = re.sub(r"(<li>.*?</li>)", r"<ul>\1</ul>", text, flags=re.DOTALL)
        text = text.replace("\n", "<br/>")  # Line breaks
        return text

    @api.depends('module_ids')
    def _generate_manual_ai(self):
        for record in self:
            if not record.module_ids:
                record.content = "<p style='color:red;'>⚠️ No module selected.</p>"
                continue

            html = """
            <div style="font-family: Georgia, 'Times New Roman', serif; padding: 40px; background: #fff; color: #2c3e50; max-width: 900px; margin: auto; border: 1px solid #ccc;">
                <h1 style="text-align:center; color:#2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px;">
                    📘 Odoo Functional User Manual
                </h1>
                <p style="text-align:center; font-size:16px; color:#7f8c8d;">Generated by AI – Powered by OpenRouter</p>
                <hr style="margin: 30px 0;" />
                <h2 style="color:#2980b9;">📚 Table of Contents</h2>
                <ul style="margin-left:20px; font-size:15px;">
            """

            # Table of Contents
            for module in record.module_ids:
                html += f"<li><a href='#{module.name}' style='text-decoration:none; color:#2980b9;'>{escape(module.name)}</a></li>"

            html += "</ul><hr style='margin: 40px 0;' />"

            # Manual for each module
            for module in record.module_ids:
                module_name = module.name
                prompt = f"""
You are an Odoo functional expert.


Generate a professional, step-by-step **functional user manual** for the Odoo module: `{module_name}`.
we also want user restriction in this 
Include:
- A high-level business flow summary.
- Each step: what users do and why.
- User roles involved.
- user restriction
- Sample actions/screens if needed (avoid deep technical terms).
- Recommendations or tips for using the module.

Avoid listing technical models like `account.account`. Focus on how real users use this module in the business flow.
"""
                ai_text = self.call_openrouter(prompt)
                formatted_ai_text = self.markdown_to_html(ai_text)

                html += f"""
                <div id="{module_name}" style="margin-top:40px; padding: 30px; background: #fafafa; border-radius: 12px; border-left: 6px solid #3498db;">
                    <h2 style="color:#34495e;">📦 Module: <span style="color:#2980b9;">{escape(module_name)}</span></h2>
                    <div style="font-size:16px; line-height:1.8; color:#2f3640;">
                        {formatted_ai_text}
                    </div>
                </div>
                <hr style="margin: 60px 0; border-top: 1px dashed #ccc;" />
                """

            html += """
                <p style="text-align:center; font-size:13px; color:#aaa; margin-top:60px;">
                    <em>Generated on-demand with 💡 AI. Styled for printing and PDF use.</em>
                </p>
            </div>
            """

            record.content = html

            # Generate PDF using wkhtmltopdf
            try:
                with tempfile.NamedTemporaryFile(delete=False, suffix='.html') as tmp_html, \
                     tempfile.NamedTemporaryFile(delete=False, suffix='.pdf') as tmp_pdf:

                    tmp_html.write(html.encode('utf-8'))
                    tmp_html.flush()

                    subprocess.run(['wkhtmltopdf', tmp_html.name, tmp_pdf.name], check=True)

                    with open(tmp_pdf.name, 'rb') as f:
                        pdf_data = f.read()
                        record.manual_file = base64.b64encode(pdf_data)
                        record.manual_filename = f"{record.name.replace(' ', '_').lower()}_{record.id}.pdf"

            except Exception as e:
                _logger.error(f"PDF generation failed: {e}")
                record.manual_file = False
                record.manual_filename = "manual_error.pdf"
